# Copyright (C) 2012 The Android Open Kang Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# This file is generated by device/samsung/espressowifi/setup-makefiles.sh
#

LOCAL_PATH := $(call my-dir)

ifeq ($(TARGET_DEVICE),espressowifi)

    include $(CLEAR_VARS)
    LOCAL_MODULE := bcm_dut
    LOCAL_MODULE_OWNER := samsung
    LOCAL_SRC_FILES := bcm_dut
    LOCAL_MODULE_TAGS := optional
    LOCAL_MODULE_CLASS := EXECUTABLES
    LOCAL_MODULE_PATH := $(TARGET_OUT)/bin
    include $(BUILD_PREBUILT)

    include $(CLEAR_VARS)
    LOCAL_MODULE := fRom
    LOCAL_MODULE_OWNER := samsung
    LOCAL_SRC_FILES := fRom
    LOCAL_MODULE_TAGS := optional
    LOCAL_MODULE_CLASS := EXECUTABLES
    LOCAL_MODULE_PATH := $(TARGET_OUT)/bin
    include $(BUILD_PREBUILT)

    include $(CLEAR_VARS)
    LOCAL_MODULE := geomagneticd
    LOCAL_MODULE_OWNER := samsung
    LOCAL_SRC_FILES := geomagneticd
    LOCAL_MODULE_TAGS := optional
    LOCAL_MODULE_CLASS := EXECUTABLES
    LOCAL_MODULE_PATH := $(TARGET_OUT)/bin
    include $(BUILD_PREBUILT)

    include $(CLEAR_VARS)
    LOCAL_MODULE := gps
    LOCAL_MODULE_OWNER := samsung
    LOCAL_SRC_FILES := gps.cer
    LOCAL_MODULE_TAGS := optional
    LOCAL_MODULE_SUFFIX := .cer
    LOCAL_MODULE_CLASS := ETC
    LOCAL_MODULE_PATH := $(TARGET_OUT)/bin
    include $(BUILD_PREBUILT)

    include $(CLEAR_VARS)
    LOCAL_MODULE := gpsd
    LOCAL_MODULE_OWNER := samsung
    LOCAL_SRC_FILES := gpsd
    LOCAL_MODULE_TAGS := optional
    LOCAL_MODULE_CLASS := EXECUTABLES
    LOCAL_MODULE_PATH := $(TARGET_OUT)/bin
    include $(BUILD_PREBUILT)

    include $(CLEAR_VARS)
    LOCAL_MODULE := orientationd
    LOCAL_MODULE_OWNER := samsung
    LOCAL_SRC_FILES := orientationd
    LOCAL_MODULE_TAGS := optional
    LOCAL_MODULE_CLASS := EXECUTABLES
    LOCAL_MODULE_PATH := $(TARGET_OUT)/bin
    include $(BUILD_PREBUILT)

    include $(CLEAR_VARS)
    LOCAL_MODULE := smc
    LOCAL_MODULE_OWNER := samsung
    LOCAL_SRC_FILES := smc.ini
    LOCAL_MODULE_TAGS := optional
    LOCAL_MODULE_SUFFIX := .ini
    LOCAL_MODULE_CLASS := ETC
    LOCAL_MODULE_PATH := $(TARGET_OUT)/bin
    include $(BUILD_PREBUILT)

    include $(CLEAR_VARS)
    LOCAL_MODULE := smc_pa
    LOCAL_MODULE_OWNER := samsung
    LOCAL_SRC_FILES := smc_pa.ift
    LOCAL_MODULE_TAGS := optional
    LOCAL_MODULE_SUFFIX := .ift
    LOCAL_MODULE_CLASS := ETC
    LOCAL_MODULE_PATH := $(TARGET_OUT)/bin
    include $(BUILD_PREBUILT)

    include $(CLEAR_VARS)
    LOCAL_MODULE := smc_pa_ctrl
    LOCAL_MODULE_OWNER := samsung
    LOCAL_SRC_FILES := smc_pa_ctrl
    LOCAL_MODULE_TAGS := optional
    LOCAL_MODULE_CLASS := EXECUTABLES
    LOCAL_MODULE_PATH := $(TARGET_OUT)/bin
    include $(BUILD_PREBUILT)

    include $(CLEAR_VARS)
    LOCAL_MODULE := tf_daemon
    LOCAL_MODULE_OWNER := samsung
    LOCAL_SRC_FILES := tf_daemon
    LOCAL_MODULE_TAGS := optional
    LOCAL_MODULE_CLASS := EXECUTABLES
    LOCAL_MODULE_PATH := $(TARGET_OUT)/bin
    include $(BUILD_PREBUILT)

    include $(CLEAR_VARS)
    LOCAL_MODULE := datapattern_420sp
    LOCAL_MODULE_OWNER := samsung
    LOCAL_SRC_FILES := datapattern_420sp.yuv
    LOCAL_MODULE_TAGS := optional
    LOCAL_MODULE_SUFFIX := .yuv
    LOCAL_MODULE_CLASS := ETC
    LOCAL_MODULE_PATH := $(TARGET_OUT)/cameradata
    include $(BUILD_PREBUILT)

    include $(CLEAR_VARS)
    LOCAL_MODULE := datapattern_front_420sp
    LOCAL_MODULE_OWNER := samsung
    LOCAL_SRC_FILES := datapattern_front_420sp.yuv
    LOCAL_MODULE_TAGS := optional
    LOCAL_MODULE_SUFFIX := .yuv
    LOCAL_MODULE_CLASS := ETC
    LOCAL_MODULE_PATH := $(TARGET_OUT)/cameradata
    include $(BUILD_PREBUILT)

    include $(CLEAR_VARS)
    LOCAL_MODULE := libAMSWiFiLibs
    LOCAL_MODULE_OWNER := samsung
    LOCAL_SRC_FILES := libAMSWiFiLibs.so
    LOCAL_MODULE_TAGS := optional
    LOCAL_MODULE_SUFFIX := .so
    LOCAL_MODULE_CLASS := PREBUILT_LIBRARIES
    LOCAL_MODULE_PATH := $(TARGET_OUT)/lib
    include $(BUILD_PREBUILT)

    include $(CLEAR_VARS)
    LOCAL_MODULE := libdomx
    LOCAL_MODULE_OWNER := samsung
    LOCAL_SRC_FILES := libdomx.so
    LOCAL_MODULE_TAGS := optional
    LOCAL_MODULE_SUFFIX := .so
    LOCAL_MODULE_CLASS := PREBUILT_LIBRARIES
    LOCAL_MODULE_PATH := $(TARGET_OUT)/lib
    include $(BUILD_PREBUILT)

    include $(CLEAR_VARS)
    LOCAL_MODULE := libI420colorconvert
    LOCAL_MODULE_OWNER := samsung
    LOCAL_SRC_FILES := libI420colorconvert.so
    LOCAL_MODULE_TAGS := optional
    LOCAL_MODULE_SUFFIX := .so
    LOCAL_MODULE_CLASS := PREBUILT_LIBRARIES
    LOCAL_MODULE_PATH := $(TARGET_OUT)/lib
    include $(BUILD_PREBUILT)

    include $(CLEAR_VARS)
    LOCAL_MODULE := libion
    LOCAL_MODULE_OWNER := samsung
    LOCAL_SRC_FILES := libion.so
    LOCAL_MODULE_TAGS := optional
    LOCAL_MODULE_SUFFIX := .so
    LOCAL_MODULE_CLASS := PREBUILT_LIBRARIES
    LOCAL_MODULE_PATH := $(TARGET_OUT)/lib
    include $(BUILD_PREBUILT)

    include $(CLEAR_VARS)
    LOCAL_MODULE := libmm_osal
    LOCAL_MODULE_OWNER := samsung
    LOCAL_SRC_FILES := libmm_osal.so
    LOCAL_MODULE_TAGS := optional
    LOCAL_MODULE_SUFFIX := .so
    LOCAL_MODULE_CLASS := PREBUILT_LIBRARIES
    LOCAL_MODULE_PATH := $(TARGET_OUT)/lib
    include $(BUILD_PREBUILT)

    include $(CLEAR_VARS)
    LOCAL_MODULE := libOMX.TI.DUCATI1.MISC.SAMPLE
    LOCAL_MODULE_OWNER := samsung
    LOCAL_SRC_FILES := libOMX.TI.DUCATI1.MISC.SAMPLE.so
    LOCAL_MODULE_TAGS := optional
    LOCAL_MODULE_SUFFIX := .so
    LOCAL_MODULE_CLASS := PREBUILT_LIBRARIES
    LOCAL_MODULE_PATH := $(TARGET_OUT)/lib
    include $(BUILD_PREBUILT)

    include $(CLEAR_VARS)
    LOCAL_MODULE := libOMX.TI.DUCATI1.VIDEO.CAMERA
    LOCAL_MODULE_OWNER := samsung
    LOCAL_SRC_FILES := libOMX.TI.DUCATI1.VIDEO.CAMERA.so
    LOCAL_MODULE_TAGS := optional
    LOCAL_MODULE_SUFFIX := .so
    LOCAL_MODULE_CLASS := PREBUILT_LIBRARIES
    LOCAL_MODULE_PATH := $(TARGET_OUT)/lib
    include $(BUILD_PREBUILT)

    include $(CLEAR_VARS)
    LOCAL_MODULE := libOMX.TI.DUCATI1.VIDEO.DECODER.secure
    LOCAL_MODULE_OWNER := samsung
    LOCAL_SRC_FILES := libOMX.TI.DUCATI1.VIDEO.DECODER.secure.so
    LOCAL_MODULE_TAGS := optional
    LOCAL_MODULE_SUFFIX := .so
    LOCAL_MODULE_CLASS := PREBUILT_LIBRARIES
    LOCAL_MODULE_PATH := $(TARGET_OUT)/lib
    include $(BUILD_PREBUILT)

    include $(CLEAR_VARS)
    LOCAL_MODULE := libOMX.TI.DUCATI1.VIDEO.DECODER
    LOCAL_MODULE_OWNER := samsung
    LOCAL_SRC_FILES := libOMX.TI.DUCATI1.VIDEO.DECODER.so
    LOCAL_MODULE_TAGS := optional
    LOCAL_MODULE_SUFFIX := .so
    LOCAL_MODULE_CLASS := PREBUILT_LIBRARIES
    LOCAL_MODULE_PATH := $(TARGET_OUT)/lib
    include $(BUILD_PREBUILT)

    include $(CLEAR_VARS)
    LOCAL_MODULE := libOMX.TI.DUCATI1.VIDEO.H264E
    LOCAL_MODULE_OWNER := samsung
    LOCAL_SRC_FILES := libOMX.TI.DUCATI1.VIDEO.H264E.so
    LOCAL_MODULE_TAGS := optional
    LOCAL_MODULE_SUFFIX := .so
    LOCAL_MODULE_CLASS := PREBUILT_LIBRARIES
    LOCAL_MODULE_PATH := $(TARGET_OUT)/lib
    include $(BUILD_PREBUILT)

    include $(CLEAR_VARS)
    LOCAL_MODULE := libOMX.TI.DUCATI1.VIDEO.MPEG4E
    LOCAL_MODULE_OWNER := samsung
    LOCAL_SRC_FILES := libOMX.TI.DUCATI1.VIDEO.MPEG4E.so
    LOCAL_MODULE_TAGS := optional
    LOCAL_MODULE_SUFFIX := .so
    LOCAL_MODULE_CLASS := PREBUILT_LIBRARIES
    LOCAL_MODULE_PATH := $(TARGET_OUT)/lib
    include $(BUILD_PREBUILT)

    include $(CLEAR_VARS)
    LOCAL_MODULE := libOMX_Core
    LOCAL_MODULE_OWNER := samsung
    LOCAL_SRC_FILES := libOMX_Core.so
    LOCAL_MODULE_TAGS := optional
    LOCAL_MODULE_SUFFIX := .so
    LOCAL_MODULE_CLASS := PREBUILT_LIBRARIES
    LOCAL_MODULE_PATH := $(TARGET_OUT)/lib
    include $(BUILD_PREBUILT)

    include $(CLEAR_VARS)
    LOCAL_MODULE := libQmageDecoder
    LOCAL_MODULE_OWNER := samsung
    LOCAL_SRC_FILES := libQmageDecoder.so
    LOCAL_MODULE_TAGS := optional
    LOCAL_MODULE_SUFFIX := .so
    LOCAL_MODULE_CLASS := PREBUILT_LIBRARIES
    LOCAL_MODULE_PATH := $(TARGET_OUT)/lib
    include $(BUILD_PREBUILT)

    include $(CLEAR_VARS)
    LOCAL_MODULE := libsecril-client
    LOCAL_MODULE_OWNER := samsung
    LOCAL_SRC_FILES := libsecril-client.so
    LOCAL_MODULE_TAGS := optional
    LOCAL_MODULE_SUFFIX := .so
    LOCAL_MODULE_CLASS := PREBUILT_LIBRARIES
    LOCAL_MODULE_PATH := $(TARGET_OUT)/lib
    include $(BUILD_PREBUILT)

    include $(CLEAR_VARS)
    LOCAL_MODULE := libstagefrighthw
    LOCAL_MODULE_OWNER := samsung
    LOCAL_SRC_FILES := libstagefrighthw.so
    LOCAL_MODULE_TAGS := optional
    LOCAL_MODULE_SUFFIX := .so
    LOCAL_MODULE_CLASS := PREBUILT_LIBRARIES
    LOCAL_MODULE_PATH := $(TARGET_OUT)/lib
    include $(BUILD_PREBUILT)

    include $(CLEAR_VARS)
    LOCAL_MODULE := libtiutils
    LOCAL_MODULE_OWNER := samsung
    LOCAL_SRC_FILES := libtiutils.so
    LOCAL_MODULE_TAGS := optional
    LOCAL_MODULE_SUFFIX := .so
    LOCAL_MODULE_CLASS := PREBUILT_LIBRARIES
    LOCAL_MODULE_PATH := $(TARGET_OUT)/lib
    include $(BUILD_PREBUILT)

    include $(CLEAR_VARS)
    LOCAL_MODULE := camera.omap4
    LOCAL_MODULE_OWNER := samsung
    LOCAL_SRC_FILES := camera.omap4.so
    LOCAL_MODULE_TAGS := optional
    LOCAL_MODULE_SUFFIX := .so
    LOCAL_MODULE_CLASS := PREBUILT_LIBRARIES
    LOCAL_MODULE_PATH := $(TARGET_OUT)/lib/hw
    include $(BUILD_PREBUILT)

    include $(CLEAR_VARS)
    LOCAL_MODULE := gps.omap4
    LOCAL_MODULE_OWNER := samsung
    LOCAL_SRC_FILES := gps.omap4.so
    LOCAL_MODULE_TAGS := optional
    LOCAL_MODULE_SUFFIX := .so
    LOCAL_MODULE_CLASS := PREBUILT_LIBRARIES
    LOCAL_MODULE_PATH := $(TARGET_OUT)/lib/hw
    include $(BUILD_PREBUILT)

    include $(CLEAR_VARS)
    LOCAL_MODULE := lights.omap4
    LOCAL_MODULE_OWNER := samsung
    LOCAL_SRC_FILES := lights.omap4.so
    LOCAL_MODULE_TAGS := optional
    LOCAL_MODULE_SUFFIX := .so
    LOCAL_MODULE_CLASS := PREBUILT_LIBRARIES
    LOCAL_MODULE_PATH := $(TARGET_OUT)/lib/hw
    include $(BUILD_PREBUILT)

    include $(CLEAR_VARS)
    LOCAL_MODULE := sensors.omap4
    LOCAL_MODULE_OWNER := samsung
    LOCAL_SRC_FILES := sensors.omap4.so
    LOCAL_MODULE_TAGS := optional
    LOCAL_MODULE_SUFFIX := .so
    LOCAL_MODULE_CLASS := PREBUILT_LIBRARIES
    LOCAL_MODULE_PATH := $(TARGET_OUT)/lib/hw
    include $(BUILD_PREBUILT)

    include $(CLEAR_VARS)
    LOCAL_MODULE := pvrsrvinit
    LOCAL_MODULE_OWNER := samsung
    LOCAL_SRC_FILES := pvrsrvinit
    LOCAL_MODULE_TAGS := optional
    LOCAL_MODULE_CLASS := EXECUTABLES
    LOCAL_MODULE_PATH := $(TARGET_OUT)/vendor/bin
    include $(BUILD_PREBUILT)

    include $(CLEAR_VARS)
    LOCAL_MODULE := libglslcompiler
    LOCAL_MODULE_OWNER := samsung
    LOCAL_SRC_FILES := libglslcompiler.so
    LOCAL_MODULE_TAGS := optional
    LOCAL_MODULE_SUFFIX := .so
    LOCAL_MODULE_CLASS := PREBUILT_LIBRARIES
    LOCAL_MODULE_PATH := $(TARGET_OUT)/vendor/lib
    include $(BUILD_PREBUILT)

    include $(CLEAR_VARS)
    LOCAL_MODULE := libIMGegl
    LOCAL_MODULE_OWNER := samsung
    LOCAL_SRC_FILES := libIMGegl.so
    LOCAL_MODULE_TAGS := optional
    LOCAL_MODULE_SUFFIX := .so
    LOCAL_MODULE_CLASS := PREBUILT_LIBRARIES
    LOCAL_MODULE_PATH := $(TARGET_OUT)/vendor/lib
    include $(BUILD_PREBUILT)

    include $(CLEAR_VARS)
    LOCAL_MODULE := libpvr2d
    LOCAL_MODULE_OWNER := samsung
    LOCAL_SRC_FILES := libpvr2d.so
    LOCAL_MODULE_TAGS := optional
    LOCAL_MODULE_SUFFIX := .so
    LOCAL_MODULE_CLASS := PREBUILT_LIBRARIES
    LOCAL_MODULE_PATH := $(TARGET_OUT)/vendor/lib
    include $(BUILD_PREBUILT)

    include $(CLEAR_VARS)
    LOCAL_MODULE := libpvrANDROID_WSEGL
    LOCAL_MODULE_OWNER := samsung
    LOCAL_SRC_FILES := libpvrANDROID_WSEGL.so
    LOCAL_MODULE_TAGS := optional
    LOCAL_MODULE_SUFFIX := .so
    LOCAL_MODULE_CLASS := PREBUILT_LIBRARIES
    LOCAL_MODULE_PATH := $(TARGET_OUT)/vendor/lib
    include $(BUILD_PREBUILT)

    include $(CLEAR_VARS)
    LOCAL_MODULE := libPVRScopeServices
    LOCAL_MODULE_OWNER := samsung
    LOCAL_SRC_FILES := libPVRScopeServices.so
    LOCAL_MODULE_TAGS := optional
    LOCAL_MODULE_SUFFIX := .so
    LOCAL_MODULE_CLASS := PREBUILT_LIBRARIES
    LOCAL_MODULE_PATH := $(TARGET_OUT)/vendor/lib
    include $(BUILD_PREBUILT)

    include $(CLEAR_VARS)
    LOCAL_MODULE := libsrv_init
    LOCAL_MODULE_OWNER := samsung
    LOCAL_SRC_FILES := libsrv_init.so
    LOCAL_MODULE_TAGS := optional
    LOCAL_MODULE_SUFFIX := .so
    LOCAL_MODULE_CLASS := PREBUILT_LIBRARIES
    LOCAL_MODULE_PATH := $(TARGET_OUT)/vendor/lib
    include $(BUILD_PREBUILT)

    include $(CLEAR_VARS)
    LOCAL_MODULE := libsrv_um
    LOCAL_MODULE_OWNER := samsung
    LOCAL_SRC_FILES := libsrv_um.so
    LOCAL_MODULE_TAGS := optional
    LOCAL_MODULE_SUFFIX := .so
    LOCAL_MODULE_CLASS := PREBUILT_LIBRARIES
    LOCAL_MODULE_PATH := $(TARGET_OUT)/vendor/lib
    include $(BUILD_PREBUILT)

    include $(CLEAR_VARS)
    LOCAL_MODULE := libusc
    LOCAL_MODULE_OWNER := samsung
    LOCAL_SRC_FILES := libusc.so
    LOCAL_MODULE_TAGS := optional
    LOCAL_MODULE_SUFFIX := .so
    LOCAL_MODULE_CLASS := PREBUILT_LIBRARIES
    LOCAL_MODULE_PATH := $(TARGET_OUT)/vendor/lib
    include $(BUILD_PREBUILT)

    include $(CLEAR_VARS)
    LOCAL_MODULE := libEGL_POWERVR_SGX540_120
    LOCAL_MODULE_OWNER := samsung
    LOCAL_SRC_FILES := libEGL_POWERVR_SGX540_120.so
    LOCAL_MODULE_TAGS := optional
    LOCAL_MODULE_SUFFIX := .so
    LOCAL_MODULE_CLASS := PREBUILT_LIBRARIES
    LOCAL_MODULE_PATH := $(TARGET_OUT)/vendor/lib/egl
    include $(BUILD_PREBUILT)

    include $(CLEAR_VARS)
    LOCAL_MODULE := libGLESv1_CM_POWERVR_SGX540_120
    LOCAL_MODULE_OWNER := samsung
    LOCAL_SRC_FILES := libGLESv1_CM_POWERVR_SGX540_120.so
    LOCAL_MODULE_TAGS := optional
    LOCAL_MODULE_SUFFIX := .so
    LOCAL_MODULE_CLASS := PREBUILT_LIBRARIES
    LOCAL_MODULE_PATH := $(TARGET_OUT)/vendor/lib/egl
    include $(BUILD_PREBUILT)

    include $(CLEAR_VARS)
    LOCAL_MODULE := libGLESv2_POWERVR_SGX540_120
    LOCAL_MODULE_OWNER := samsung
    LOCAL_SRC_FILES := libGLESv2_POWERVR_SGX540_120.so
    LOCAL_MODULE_TAGS := optional
    LOCAL_MODULE_SUFFIX := .so
    LOCAL_MODULE_CLASS := PREBUILT_LIBRARIES
    LOCAL_MODULE_PATH := $(TARGET_OUT)/vendor/lib/egl
    include $(BUILD_PREBUILT)

    include $(CLEAR_VARS)
    LOCAL_MODULE := gralloc.omap4
    LOCAL_MODULE_OWNER := samsung
    LOCAL_SRC_FILES := gralloc.omap4.so
    LOCAL_MODULE_TAGS := optional
    LOCAL_MODULE_SUFFIX := .so
    LOCAL_MODULE_CLASS := PREBUILT_LIBRARIES
    LOCAL_MODULE_PATH := $(TARGET_OUT)/vendor/lib/hw
    include $(BUILD_PREBUILT)

    include $(CLEAR_VARS)
    LOCAL_MODULE := prebuilt_hwcomposer.omap4
    LOCAL_MODULE_OWNER := samsung
    LOCAL_SRC_FILES := hwcomposer.omap4.so
    LOCAL_MODULE_TAGS := optional
    LOCAL_MODULE_SUFFIX := .so
    LOCAL_MODULE_CLASS := PREBUILT_LIBRARIES
    LOCAL_MODULE_PATH := $(TARGET_OUT)/vendor/lib/hw
    LOCAL_MODULE_NAME := hwcomposer.omap4.so
    include $(BUILD_PREBUILT)

endif
