# Copyright (C) 2012 The Android Open Kang Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# This file is generated by device/samsung/espressowifi/setup-makefiles.sh
#

PRODUCT_PACKAGES := \
    bcm_dut \
    fRom \
    geomagneticd \
    gps \
    gpsd \
    orientationd \
    smc \
    smc_pa \
    smc_pa_ctrl \
    tf_daemon \
    datapattern_420sp \
    datapattern_front_420sp \
    libAMSWiFiLibs \
    libdomx \
    libI420colorconvert \
    libion \
    libmm_osal \
    libOMX.TI.DUCATI1.MISC.SAMPLE \
    libOMX.TI.DUCATI1.VIDEO.CAMERA \
    libOMX.TI.DUCATI1.VIDEO.DECODER.secure \
    libOMX.TI.DUCATI1.VIDEO.DECODER \
    libOMX.TI.DUCATI1.VIDEO.H264E \
    libOMX.TI.DUCATI1.VIDEO.MPEG4E \
    libOMX_Core \
    libQmageDecoder \
    libsecril-client \
    libstagefrighthw \
    libtiutils \
    camera.omap4 \
    gps.omap4 \
    lights.omap4 \
    sensors.omap4 \
    pvrsrvinit \
    libglslcompiler \
    libIMGegl \
    libpvr2d \
    libpvrANDROID_WSEGL \
    libPVRScopeServices \
    libsrv_init \
    libsrv_um \
    libusc \
    libEGL_POWERVR_SGX540_120 \
    libGLESv1_CM_POWERVR_SGX540_120 \
    libGLESv2_POWERVR_SGX540_120 \
    gralloc.omap4 \
    prebuilt_hwcomposer.omap4
