# Copyright (C) 2010 The Android Open Source Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/samsung/toroplus/extract-files.sh - DO NOT EDIT

# All the blobs necessary for toroplus
PRODUCT_PACKAGES += \
    bcm4330 \
    BIP \
    HiddenMenu \
    SDM \
    SecPhone \
    SyncMLSvc \
    gps.omap4 \
    lib_gsd4t \
    libdrmdecrypt \
    libsec-ril_lte \
    libsyncml_core \
    libsyncml_port \
    libsecril-client \
    sirfgps
