#!/system/xbin/sh
echo "Glitch in-call boost settings manager"
echo "kanged from KGB and enhanced by Efpophis"
echo ""
# Includes
. /system/bin/lib.sh

# Abort conditions
root_uid_check
af $BOOST_RCV $BOOST_BT $BOOST_SPK $BOOST_HP $MIC_RCV $MIC_SPK $MIC_HP $MIC_HP_NO || err_exit "Kernel does not support in-call boost settings!"

# Defines

if [ -d /sys/devices/virtual/misc/wm8994_call_audio ]; then
  DEV_PATH=/sys/devices/virtual/misc/wm8994_call_audio
else
  DEV_PATH=/sys/devices/virtual/misc/voodoo_sound
fi

BOOST_RCV=${DEV_PATH}/incall_boost_rcv
BOOST_BT=${DEV_PATH}/incall_boost_bt
BOOST_SPK=${DEV_PATH}/incall_boost_spk
BOOST_HP=${DEV_PATH}/incall_boost_hp
MIC_RCV=${DEV_PATH}/incall_mic_gain_rcv
MIC_SPK=${DEV_PATH}/incall_mic_gain_spk
MIC_HP=${DEV_PATH}/incall_mic_gain_hp
MIC_HP_NO=${DEV_PATH}/incall_mic_gain_hp_no_mic
BOOST_SCRIPT=/system/etc/init.d/90call_vol
REMOUNTED=0

# Functions
show_boost()
{
B_RCV=$(cat $BOOST_RCV)
B_BT=$(cat $BOOST_BT)
B_SPK=$(cat $BOOST_SPK)
B_HP=$(cat $BOOST_HP)
echo "Displaying current in-call boost settings:

	RCV	BT	SPK	HP
	$B_RCV	$B_BT	$B_SPK	$B_HP

    0: +0dB, 1: +6dB, 2: +12dB, 3: +18dB"
}

show_mic_gain()
{
M_RCV=$(cat $MIC_RCV)
M_SPK=$(cat $MIC_SPK)
M_HP=$(cat $MIC_HP)
M_HP_NO=$(cat $MIC_HP_NO)
echo "Current mic gain settings:

  RCV SPK HP HP_NO_MIC
  $M_RCV  $M_SPK  $M_HP $M_HP_NO
  
    0: -16.5db  11: 0db   31: 30db  0 - 31, +1.5db per unit"
}

set_boost()
{
echo $1 > $BOOST_RCV &&
echo $2 > $BOOST_BT &&
echo $3 > $BOOST_SPK &&
echo $4 > $BOOST_HP &&
echo "In-call boost values set to $1, $2, $3, $4" || err_exit "Failed to set in-call boost values!"
}

set_mic_gain()
{
echo $1 > $MIC_RCV &&
echo $2 > $MIC_SPK &&
echo $3 > $MIC_HP &&
echo $4 > $MIC_HP_NO &&
echo "In-call mic gain values set to $1, $2, $3, $4" || err_exit "Failed to set in-call mic gain values!"
}

read_check()
{
while [ 1 ]; do
	read -p "$1" i
	if [ $i -eq $i 2>/dev/null ] && [ $i -ge 0 ] && [ $i -le 3 ]; then
		echo $i
		break
	fi
done
}

read_check_mic()
{
while [ 1 ]; do
	read -p "$1" i
	if [ $i -eq $i 2>/dev/null ] && [ $i -ge 0 ] && [ $i -le 31 ]; then
		echo $i
		break
	fi
done
}

write_boot()
{
[ -f $1 ] && echo -n "Overwriting existing boot script at $1... " || echo -n "Installing boot script to $1... "
echo "#!/system/bin/sh
echo $B_RCV > $BOOST_RCV
echo $B_BT > $BOOST_BT
echo $B_SPK > $BOOST_SPK
echo $B_HP > $BOOST_HP
echo $M_RCV > $MIC_RCV
echo $M_SPK > $MIC_SPK
echo $M_HP > $MIC_HP
echo $M_HP_NO > $MIC_HP_NO" > $1 && chown 0.0 $1 && chmod 755 $1 &&
echo "done!" || err_exit "Failed to install boot script!"
}

# Script body
if system_is_ro; then
	system_rw
	REMOUNTED=1
fi

if [ "$1" = "enable" ]; then
	show_boost
	echo ""
	show_mic_gain
	echo ""
	echo "    Defaults: 2, 2, 2, 2"
	echo ""
	B_RCV="$(read_check '    New RECEIVER boost value:	')"
	B_BT="$(read_check '    New BLUETOOTH boost value:	')"
	B_SPK="$(read_check '    New SPEAKER boost value:	')"
	B_HP="$(read_check '    New HEADPHONE boost value:	')"
	M_RCV="$(read_check_mic '    New RECEIVER mic gain value:  ')"
	M_SPK="$(read_check_mic '    New SPEAKER mic gain value:  ')"
	M_HP="$(read_check_mic '    New HEADPHONE mic gain value:  ')"
	M_HP_NO="$(read_check_mic '    New HEADPHONE_NO_MIC mic gain value:  ')"
	echo ""
	set_boost $B_RCV $B_BT $B_SPK $B_HP
	set_mic_gain $M_RCV $M_SPK $M_HP $M_HP_NO
	write_boot $BOOST_SCRIPT
	echo ""
	show_boost
	echo ""
	show_mic_gain
elif [ "$1" = "disable" ]; then
	show_boost
	echo ""
	show_mic_gain
	echo ""
	echo "Resetting in-call boost values to defaults."
	set_boost 2 2 2 2
	set_mic_gain 21 18 29 18
	probe_del_boot $BOOST_SCRIPT
	echo ""
	show_boost
	echo ""
	show_mic_gain
elif [ "$1" = "show" ]; then
	show_boost
	echo ""
	show_mic_gain
elif [ $1 ]; then
	echo "Unrecognized option: $1"; echo ""; show_options "callboost"
else
	show_options "callboost"
fi

[ "$REMOUNTED" = "1" ] && system_ro

echo "
Finished."
